version: "3.7"
services:
# base: # Base image for the appliances
#   image: lnlscon/epics-archiver-base:tomcat9-jdk15
#   command: sleep infinity

  single_1:
    hostname: epics-archiver
    image: lnlscon/epics-archiver-single:tomcat9-jdk15-epicsR7.0.5-2021-03-01
    environment:
      GITHUB_APPLIANCES_BRANCH: "PR-JDK12-master"
      ARCHAPPL_MYIDENTITY: "lnls_control_appliance_1"
      USE_AUTHENTICATION: "true"
    ports:
      - 11000:11000
      - 11995:11995
      - 11996:11996
      - 11997:11997
      - 11998:11998
    env_file:
      - ./.sql.env
      - ./.ldap.env
      - ./.archiver.env
    volumes:
      - ./images-single/configuration/lnls_appliances.xml:/opt/epics-archiver-appliances/configuration/lnls_appliances.xml:rw
      - ./images-single/configuration/lnls_policies.py:/opt/epics-archiver-appliances/configuration/lnls_policies.py:ro

  single_2:
    hostname: epics-archiver
    image: lnlscon/epics-archiver-single:tomcat9-jdk15-epicsR7.0.5-2021-03-01
    environment:
      GITHUB_APPLIANCES_BRANCH: "PR-JDK12-master"
      ARCHAPPL_MYIDENTITY: "lnls_control_appliance_2"
      USE_AUTHENTICATION: "true"
    ports:
      - 12000:12000
      - 12995:12995
      - 12996:12996
      - 12997:12997
      - 12998:12998
    env_file:
      - ./.sql.env
      - ./.ldap.env
      - ./.archiver.env
    volumes:
      - ./images-single/configuration/lnls_appliances.xml:/opt/epics-archiver-appliances/configuration/lnls_appliances.xml:rw
      - ./images-single/configuration/lnls_policies.py:/opt/epics-archiver-appliances/configuration/lnls_policies.py:ro

  epics-archiver-mysql-db:
    hostname: epics-archiver-mysql-db
    image: lnlscon/epics-archiver-mysql-db:latest
    env_file:
      - ./.sql.env
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./db:/var/lib/mysql:rw
